// ── STATE ──
var API = 'http://localhost:8800/api';
var currentView = 'browse';
var currentBookId = null;
var currentSaveId = null;
var paragraphQueue = [];
var paragraphIndex = 0;
var storyHistory = [];
var longPressTimer = null;
var autoPlayInterval = null;
var isAutoPlaying = false;
var actionMode = 'normal';
var bookDetailCache = {};
var genStartTime = 0;
var genTimerInterval = null;
var currentMemo = '';
var currentReferenceSections = [];
var availableSections = [];
